# Site settings
author: Erica Murdock-Waters
title: ...emw...
header-img: img/home-bg.png
email: ericahpa@gmail.com
copyright_name: Erica Murdock-Waters
description: > # this means to ignore newlines until "baseurl:"
  dwell in possibilities
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  eleemw

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
